"""delete_category_from_questions

Revision ID: 1ace8f66508f
Revises: 397418b05213
Create Date: 2025-09-18 15:17:39.970524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ace8f66508f'
down_revision = '397418b05213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
