"""add_prefecture_foreign_key_constraints_to_clubs

Revision ID: 1ff370cbfdbe
Revises: 632f77049f30
Create Date: 2025-09-20 05:10:45.233947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff370cbfdbe'
down_revision = '632f77049f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prefectures', ['prefecture_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
