"""create_stadiums_table

Revision ID: 45176d0c9e38
Revises: c3efcc23989a
Create Date: 2025-10-21 15:23:31.257297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45176d0c9e38'
down_revision = 'c3efcc23989a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadiums',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('capacity', sa.Integer(),
                              server_default='15000', nullable=False),
                    sa.Column('accessibility', sa.Float(),
                              server_default='0.5', nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_stadium_id',
                            sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None, 'stadiums', ['main_stadium_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('main_stadium_id')

    op.drop_table('stadiums')
    # ### end Alembic commands ###
