"""add category to questions

Revision ID: 526b269c13c3
Revises: 7e0a92e72a81
Create Date: 2025-09-14 07:19:42.701124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526b269c13c3'
down_revision = '7e0a92e72a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_choices_qid_text'), type_='unique')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_questions_text'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_questions_text'), ['text'])
        batch_op.drop_column('category')

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_choices_qid_text'), ['question_id', 'text'])

    # ### end Alembic commands ###
