"""add_feature_amount_columns_to_clubs

Revision ID: 531c48ae0cd2
Revises: 1ace8f66508f
Create Date: 2025-09-18 15:36:17.955468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531c48ae0cd2'
down_revision = '1ace8f66508f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength_long_term',
                            sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(sa.Column('strength_short_term',
                            sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(sa.Column('domestic_titles',
                                      sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('international_titles',
                                      sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('popularity_score',
                                      sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(
            sa.Column('supporter_heat', sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(sa.Column('financial_power',
                                      sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(sa.Column('ticket_availability',
                                      sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(sa.Column(
            'rivalry_intensity_preference', sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(sa.Column('play_style_attack',
                                      sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(sa.Column('play_style_defense',
                                      sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(sa.Column('play_style_youth',
                                      sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(
            sa.Column('stadium_access', sa.Float(), nullable=False, server_default="0.5"))
        batch_op.add_column(sa.Column(
            'stadium_capacity', sa.Integer(), nullable=False, server_default="15000"))
        batch_op.add_column(sa.Column(
            'stadium_event_richness', sa.Float(), nullable=False, server_default="0.5"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('stadium_event_richness')
        batch_op.drop_column('stadium_capacity')
        batch_op.drop_column('stadium_access')
        batch_op.drop_column('play_style_youth')
        batch_op.drop_column('play_style_defense')
        batch_op.drop_column('play_style_attack')
        batch_op.drop_column('rivalry_intensity_preference')
        batch_op.drop_column('ticket_availability')
        batch_op.drop_column('financial_power')
        batch_op.drop_column('supporter_heat')
        batch_op.drop_column('popularity_score')
        batch_op.drop_column('international_titles')
        batch_op.drop_column('domestic_titles')
        batch_op.drop_column('strength_short_term')
        batch_op.drop_column('strength_long_term')

    # ### end Alembic commands ###
