"""add_short_name_to_clubs

Revision ID: 611de1bf4639
Revises: f6d9de545a62
Create Date: 2025-11-28 00:56:23.788134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611de1bf4639'
down_revision = 'f6d9de545a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.String(length=120), server_default='NONE', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###
