"""create_prefectures_table

Revision ID: 632f77049f30
Revises: 88c1d775f09a
Create Date: 2025-09-20 03:18:06.608255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632f77049f30'
down_revision = '88c1d775f09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefectures')
    # ### end Alembic commands ###
