"""rename_attendance_average_to_home_attendance_at_clubs

Revision ID: 710ce0bfcbab
Revises: cd8322239ced
Create Date: 2025-09-30 15:56:19.958750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710ce0bfcbab'
down_revision = 'cd8322239ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_attendance', sa.Integer(), server_default='10000', nullable=False))
        batch_op.drop_column('attendance_average')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_average', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'10000'::double precision"), autoincrement=False, nullable=False))
        batch_op.drop_column('home_attendance')

    # ### end Alembic commands ###
