"""add_columns_to_clubs

Revision ID: 88c1d775f09a
Revises: 531c48ae0cd2
Create Date: 2025-09-20 03:02:26.555787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c1d775f09a'
down_revision = '531c48ae0cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('emblem_url', sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column('team_color', sa.String(length=7), nullable=True))
        batch_op.add_column(
            sa.Column('website_url', sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column('main_stadium', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column('prefecture_id', sa.Integer(), nullable=False, server_default="1"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('prefecture_id')
        batch_op.drop_column('description')
        batch_op.drop_column('main_stadium')
        batch_op.drop_column('website_url')
        batch_op.drop_column('team_color')
        batch_op.drop_column('emblem_url')

    # ### end Alembic commands ###
