"""rename_play_style_youth_to_youth_promotion_score_in_clubs

Revision ID: c3efcc23989a
Revises: 710ce0bfcbab
Create Date: 2025-10-20 13:32:57.609102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3efcc23989a'
down_revision = '710ce0bfcbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youth_promotion_score', sa.Float(), server_default='0.5', nullable=False))
        batch_op.drop_column('play_style_youth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('play_style_youth', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False))
        batch_op.drop_column('youth_promotion_score')

    # ### end Alembic commands ###
