"""add_stadium_latitude_longitude_and_fix_columns_to_clubs

Revision ID: ccd6931af9f8
Revises: 1ff370cbfdbe
Create Date: 2025-09-22 13:57:20.031664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd6931af9f8'
down_revision = '1ff370cbfdbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('main_stadium_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stadium_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stadium_longitude', sa.Float(), nullable=True))
        batch_op.drop_column('emblem_url')
        batch_op.drop_column('main_stadium')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_stadium', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emblem_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('stadium_longitude')
        batch_op.drop_column('stadium_latitude')
        batch_op.drop_column('main_stadium_name')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
