"""add_attendance_average_to_clubs

Revision ID: cd8322239ced
Revises: ccd6931af9f8
Create Date: 2025-09-26 15:17:59.150226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8322239ced'
down_revision = 'ccd6931af9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_average', sa.Float(), server_default='10000', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('attendance_average')

    # ### end Alembic commands ###
