"""add_win_columns_to_clubs

Revision ID: e0e8f58e3077
Revises: 45176d0c9e38
Create Date: 2025-10-22 16:53:50.287063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e8f58e3077'
down_revision = '45176d0c9e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('win_j1', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('win_j2', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('win_j3', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('win_emperor', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('win_levain', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('win_acl', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('win_acl2', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('win_acl2')
        batch_op.drop_column('win_acl')
        batch_op.drop_column('win_levain')
        batch_op.drop_column('win_emperor')
        batch_op.drop_column('win_j3')
        batch_op.drop_column('win_j2')
        batch_op.drop_column('win_j1')

    # ### end Alembic commands ###
