"""add_time_required_columns_to_stadiums

Revision ID: fc55c4bad6b2
Revises: 611de1bf4639
Create Date: 2026-01-02 13:41:17.563800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc55c4bad6b2'
down_revision = '611de1bf4639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadiums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walking_time_required', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bus_time_required', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadiums', schema=None) as batch_op:
        batch_op.drop_column('bus_time_required')
        batch_op.drop_column('walking_time_required')

    # ### end Alembic commands ###
